import { 
	bauhausLight, bauhausDark,
	constructionLight, constructionDark,
	doomLight, doomDark,
	eightiesLight, eightiesDark,
	hogwartsLight, hogwartsDark,
	iznikLight, iznikDark,
	kaamosLight, kaamosDark,
	kaibabLight, kaibabDark,
	lotrLight, lotrDark,
	muranoLight, muranoDark,
	neutralLight, neutralDark,
	ninetiesLight, ninetiesDark,
	nostromoLight, nostromoDark,
	pentelicLight, pentelicDark,
	pompeianLight, pompeianDark,
	sheffieldSteelLight, sheffieldSteelDark,
	starWarsLight, starWarsDark,
	thebanTombLight, thebanTombDark,
	tiznitSilverLight, tiznitSilverDark,
	tresRichesHeuresLight, tresRichesHeuresDark,
	ukiyoELight, ukiyoEDark,
	wariLight, wariDark,
	washiLight, washiDark,
	yosemiteLight, yosemiteDark,
} from "./themes/index.js";

export const themes: ITheme[] = [
	neutralLight, neutralDark,
	bauhausLight, bauhausDark,
	constructionLight, constructionDark,
	doomLight, doomDark,
	eightiesLight, eightiesDark,
	hogwartsLight, hogwartsDark,
	// iznikLight, iznikDark,
	// kaamosLight, kaamosDark,
	// kaibabLight, kaibabDark,
	// lotrLight, lotrDark,
	// muranoLight, muranoDark,
	ninetiesLight, ninetiesDark,
	// nostromoLight, nostromoDark,
	// pentelicLight, pentelicDark,
	// pompeianLight, pompeianDark,
	// sheffieldSteelLight, sheffieldSteelDark,
	// starWarsLight, starWarsDark,
	// thebanTombLight, thebanTombDark,
	// tiznitSilverLight, tiznitSilverDark,
	// tresRichesHeuresLight, tresRichesHeuresDark,
	// ukiyoELight, ukiyoEDark,
	// wariLight, wariDark,
	// washiLight, washiDark,
	// yosemiteLight, yosemiteDark,
];